title: gT0 blog
description: My Personal Blog
author: Giovanni Tommasini
github: https://github.com/tommasinigiovanni
about: Ogni persona che incontri sta combattendo una battaglia di cui non sai nulla. Sii gentile. Sempre
disqus_shortname: giovannitommasini
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/giovanni.tommasini"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/giovannitommasini"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/tommasinigiovanni"

share:
  twitter_username: giovi_tom
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://tommasinigiovanni.github.io/blog/"
baseurl: "/blog/"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
