title: gT0's blog
description: computer science, IT, linux, system administrator and other disquisitions
author: Giovanni Tommasini
github: https://github.com/tommasinigiovanni
about: Be pitiful, for every man is fighting a hard battle. <br><i>Ogni persona che incontri sta combattendo una battaglia di cui non sai nulla. Sii gentile. Sempre.</i><br><a href="http://www.gt0.it">www.gT0.it</a>
disqus_shortname: giovanni_tommasini
google_analytics: UA-392753-10

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/giovanni.tommasini"
    - icon: fa-twitter
      link: "https://twitter.com/giovi_tom"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/giovannitommasini"
    - icon: fa-stack-exchange
      link: "http://stackoverflow.com/users/6801150/giovanni-tommasini"
    - icon: fa-github
      link: "https://github.com/tommasinigiovanni"

share:
  twitter_username: giovi_tom
  fb_appid:

urls:
    - text: About Me
      url: about/
    - text: My Projects
      url: projects/
    - text: XML Feed
      url: feed.xml

url: "https://tommasinigiovanni.github.io/blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
