title: gT0's blog
description: computer science, IT, linux, system administrator and other disquisitions
author: Giovanni Tommasini
github: https://github.com/tommasinigiovanni
about: Be pitiful, for every man is fighting a hard battle. (Ogni persona che incontri sta combattendo una battaglia di cui non sai nulla. Sii gentile. Sempre).<br>(www.gT0.it)[http://www.gt0.it]
disqus_shortname: giovannitommasini
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/giovanni.tommasini"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/giovannitommasini"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/tommasinigiovanni"

share:
  twitter_username: giovi_tom
  fb_appid:

urls:
    - text: About Me
      url: {{ site.url }}/about/
    - text: My Projects
      url: {{ site.url }}/projects/
    - text: XML Feed
      url: {{ site.url }}/feed.xml

url: "https://tommasinigiovanni.github.io/blog"
baseurl: "/blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
